/**
 * Subscan Portfolio 涵蓋之 Substrate 網路 — 與官方 API 文件一致。
 * 來源：https://support.subscan.io/ →「API Endpoints」表格，僅收錄 Status 為 **live** 之列（不含 test）。
 * 文件註明列表可能手動更新；若 Subscan 新增網路請比照文件增列。
 *
 * 格式：[列表顯示名稱, API base URL]
 */
export const SUBSCAN_LIVE_NETWORKS_FOR_PORTFOLIO = Object.freeze([
  ['Acala', 'https://acala.api.subscan.io'],
  ['Altair', 'https://altair.api.subscan.io'],
  ['Asset Hub Kusama', 'https://assethub-kusama.api.subscan.io'],
  ['Asset Hub Polkadot', 'https://assethub-polkadot.api.subscan.io'],
  ['Astar', 'https://astar.api.subscan.io'],
  ['Autonomys', 'https://autonomys.api.subscan.io'],
  ['Avail', 'https://avail.api.subscan.io'],
  ['Basilisk', 'https://basilisk.api.subscan.io'],
  ['Bifrost Kusama', 'https://bifrost-kusama.api.subscan.io'],
  ['Bifrost Polkadot', 'https://bifrost.api.subscan.io'],
  ['Bridge Hub Kusama', 'https://bridgehub-kusama.api.subscan.io'],
  ['Bridge Hub Polkadot', 'https://bridgehub-polkadot.api.subscan.io'],
  ['Centrifuge', 'https://centrifuge-standalone-history.api.subscan.io'],
  ['Centrifuge Parachain', 'https://centrifuge.api.subscan.io'],
  ['Collectives', 'https://collectives-polkadot.api.subscan.io'],
  ['Coretime Kusama', 'https://coretime-kusama.api.subscan.io'],
  ['Coretime Polkadot', 'https://coretime-polkadot.api.subscan.io'],
  ['Creditcoin', 'https://cc-enterprise.api.subscan.io'],
  ['Creditcoin CC3', 'https://creditcoin.api.subscan.io'],
  ['Crust', 'https://crust.api.subscan.io'],
  ['Crust Parachain', 'https://crust-parachain.api.subscan.io'],
  ['Darwinia', 'https://darwinia.api.subscan.io'],
  ['Energy Web X', 'https://energywebx.api.subscan.io'],
  ['Enjin Matrix', 'https://matrix.api.subscan.io'],
  ['Enjin Relay', 'https://enjin.api.subscan.io'],
  ['Heima', 'https://heima.api.subscan.io'],
  ['Humanode', 'https://humanode.api.subscan.io'],
  ['Hydration', 'https://hydration.api.subscan.io'],
  ['Karura', 'https://karura.api.subscan.io'],
  ['Krest', 'https://krest.api.subscan.io'],
  ['Kusama', 'https://kusama.api.subscan.io'],
  ['Manta', 'https://manta.api.subscan.io'],
  ['Midnight', 'https://midnight.api.subscan.io'],
  ['Moonbeam', 'https://moonbeam.api.subscan.io'],
  ['Moonriver', 'https://moonriver.api.subscan.io'],
  ['Mythos', 'https://mythos.api.subscan.io'],
  ['NeuroWeb', 'https://neuroweb.api.subscan.io'],
  ['Peaq', 'https://peaq.api.subscan.io'],
  ['Pendulum', 'https://pendulum.api.subscan.io'],
  ['People Kusama', 'https://people-kusama.api.subscan.io'],
  ['People Polkadot', 'https://people-polkadot.api.subscan.io'],
  ['Phala', 'https://phala.api.subscan.io'],
  ['Polkadot', 'https://polkadot.api.subscan.io'],
  ['Polymesh', 'https://polymesh.api.subscan.io'],
  ['Reef', 'https://reef.api.subscan.io'],
  ['Robonomics', 'https://robonomics.api.subscan.io'],
  ['Shiden', 'https://shiden.api.subscan.io'],
  ['Space and Time', 'https://sxt.api.subscan.io'],
  ['Tanssi', 'https://tanssi.api.subscan.io'],
  ['Vara', 'https://vara.api.subscan.io'],
  ['VFlow', 'https://vflow.api.subscan.io'],
  ['zkVerify', 'https://zkverify.api.subscan.io']
])
